baseURL: 'https://futo-horio.dev'
languageCode: 'ja-jp'
title: 'Dev Notes'
theme: 'PaperMod'
googleAnalytics: 'G-FNBTZFKERP'

label:
  text: 'Home'

params:
    env: production
    author: Me
    homeInfoParams:
        Title: Dev Notes 
        Content: >
          開発ノート

    socialIcons:
        - name: 'GitHub'
          url: 'https://github.com/Futo23'
        - name: 'Twitter'
          url: 'https://twitter.com/Futo_Horio'
        - name: 'SpeakerDeck'
          url: 'https://speakerdeck.com/futo23'
        - name: RSS
          url:  'index.xml'

    showShareButtons: false
    showBreadCrumbs: false
    showReadingTime: true
    comments: true

menu:
  main:
      - name: Tags
        url: tags/
        weight: 10