baseURL: 'https://black-field-0119efb00.2.azurestaticapps.net/'
languageCode: 'ja-jp'
title: 'Dev Notes'
theme: 'PaperMod'

label:
  text: 'Home'

params:
    env: production
    author: Me
    homeInfoParams:
        Title: Dev Notes 
        Content: >
          開発ノート

    DateFormat: 'January 1, 2023'
    socialIcons:
        - name: 'github'
          url: 'https://github.com/Futo23'
        - name: 'twitter'
          url: 'https://twitter.com/Futo_Horio'
        - name: 'qiita'
          url: 'https://qiita.com/Futo_Horio'
        - name: Rss
          url:  'index.xml'

    showShareButtons: false
    showBreadCrumbs: false
    showReadingTime: true
    comments: true

menu:
  main:
      - name: Tags
        url: tags/
        weight: 10